[versions]
springBoot = '3.5.9'
freefairLombokVersion = '9.1.0'
lombok = '1.18.42'
jacoco = '0.8.13'
spotless = '8.1.0'
jspecify = '1.0.0'
checkstyle = '12.3.0'
pmd-tool = '7.19.0'
dependencycheck = '12.1.9'
commons-lang3 = '3.20.0'
groovy = '5.0.3'
spock = '2.4-groovy-5.0'
openapi-generator = '7.18.0'
swagger-annotations = '2.2.41'
jackson-databind-nullable = '0.2.8'
jakarta-validation = '3.1.1'

[libraries]
spring-boot-devtools = { module = 'org.springframework.boot:spring-boot-devtools', version.ref = 'springBoot' }
jspecify = { module = 'org.jspecify:jspecify', version.ref = 'jspecify' }
commons-lang3 = { module = 'org.apache.commons:commons-lang3', version.ref = 'commons-lang3' }
groovy-bom = { module = 'org.apache.groovy:groovy-bom', version.ref = 'groovy' }
spock-bom = { module = 'org.spockframework:spock-bom', version.ref = 'spock' }
swagger-annotations = { module = 'io.swagger.core.v3:swagger-annotations', version.ref = 'swagger-annotations' }
jackson-databind-nullable = { module = 'org.openapitools:jackson-databind-nullable', version.ref = 'jackson-databind-nullable' }
jakarta-validation = { module = 'jakarta.validation:jakarta.validation-api', version.ref = 'jakarta-validation' }

[bundles]
sec-fix = ['commons-lang3']

[plugins]
spring-boot = { id = 'org.springframework.boot', version.ref = 'springBoot' }
lombok = { id = 'io.freefair.lombok', version.ref = 'freefairLombokVersion' }
spotless = { id = 'com.diffplug.spotless', version.ref = 'spotless' }
dependencycheck = { id = 'org.owasp.dependencycheck', version.ref = 'dependencycheck' }
openapi-generator = { id = 'org.openapi.generator', version.ref = 'openapi-generator' }
